# fly.toml app configuration file generated for dashboard3 on 2023-11-27T12:04:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dashboard3"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Services Section
[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  # Additional Settings
  processes = ["app"]

  # Ports Section
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

[[services]]
  internal_port = 8081
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  # Additional Settings
  processes = ["app"]

  # Ports Section
  [[services.ports]]
    handlers = ["http"]
    port = 8081
    force_https = true

# Mounts Section
[mounts]
  source = "myapp_data"
  destination = "/data"
  processes = ["disk"] # optional - attach volumes to Machines that belong to one or more process groups
  initial_size = "20GB" # optional - the size of the volume created on first deploy
  auto_extend_size_threshold = 80 # optional - threshold for auto-extending volume size
  auto_extend_size_increment = "1GB" # optional - increment for auto-extending volume size
  auto_extend_size_limit = "5GB" # optional - limit for auto-extending volume size
